# Generated by Django 5.1.2 on 2024-10-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_project_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="title",
            field=models.CharField(max_length=64),
        ),
    ]
